### ISSUE TITLE
Future of the project?

### ISSUE THREAD

**Issue by refi64** [dw/cpp-elementtree#1]
The project description says this is incomplete, but there haven't been any updates since 2013. Is this dead?

**Comment by dw** [comment]
Yes, it's dead for the time being. Mosty I'm not working with XML/RSS/C++ at the moment. It needs lots of testing, and I never did much of that. Fork, embrace and extend!

**Comment by dw** [comment]
Hi @kirbyfan64 

I got a random gust of wind in the sails and fixed a ton of bugs and wrote tests covering all the basic functionality. At least the test suite passes without any valgrind errors, and simple manipulations work. It's still missing some useful stuff, like controlling the libxml2 parser, but generally I'd say this is in a decent state now.

**Comment by refi64** [comment]
:D
